name: "Project CI"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  call-reusable-ci:
    uses: bestdevopsengineer/composite_action/.github/workflows/maven-ci.yml@main
    with:
      java-version: "21"
      run-tests: true
